# -*- coding: utf-8 -*-
"""XGBoost_Discrete.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-s9Dvhb1AiXTEG2J0rPLU3Wc_hWK1FP-
"""

!pip install TA-Lib mplfinance

"""# XGBoost Trading Strategy: Momentum & Mean Reversion
This script constructs a machine learning trading strategy using XGBoost.
It calculates features based on Volume, Moving Averages (5D, 20D), RSI, and the Fast Stochastic Oscillator.
The target variable is the standardized 3-day cumulative percentage change of the closing price.
"""

import yfinance as yf
import pandas as pd
import numpy as np
import talib
import xgboost as xgb
import matplotlib.pyplot as plt
import mplfinance as mpf
from sklearn.metrics import accuracy_score, classification_report
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

# Global Configuration
TICKER = "SPY"
START_DATE = "2020-01-01"
END_DATE = "2025-12-31"

"""## 1. Data Acquisition
We fetch historical daily price data using the `yfinance` library.
"""

def fetch_stock_data(ticker, start_date, end_date):
    """Fetches historical stock data from Yahoo Finance."""
    df = yf.download(ticker, start=start_date, end=end_date, progress=False)
    # yfinance sometimes returns a MultiIndex column structure, flatten it if necessary
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.droplevel(1)
    return df.dropna()

"""## 2. Base Technical Indicators
Using TA-Lib, we calculate the foundational technical indicators required for our custom features:
5D SMA, 20D SMA, RSI (14-day default), and Fast Stochastic (%K, %D)[cite: 1].
"""

def calculate_base_indicators(df):
    """Calculates base technical indicators using TA-Lib."""
    df = df.copy()

    # Simple Moving Averages[cite: 1]
    df['SMA_5'] = talib.SMA(df['Close'], timeperiod=5)
    df['SMA_20'] = talib.SMA(df['Close'], timeperiod=20)

    # Volume Moving Averages
    df['Vol_SMA_5'] = talib.SMA(df['Volume'], timeperiod=5)
    df['Vol_SMA_20'] = talib.SMA(df['Volume'], timeperiod=20)

    # Relative Strength Index[cite: 1]
    df['RSI'] = talib.RSI(df['Close'], timeperiod=14)

    # Fast Stochastic Oscillator
    df['fastk'], df['fastd'] = talib.STOCHF(df['High'], df['Low'], df['Close'],
                                            fastk_period=5, fastd_period=3, fastd_matype=0)
    return df.dropna()

"""## 3. Custom Feature Engineering
We translate the base indicators into the specific, ordinal machine learning features outlined in the strategy proposal.
"""

def build_custom_features(df):
    """Constructs the ordinal ML features based on the proposed strategy logic."""
    df = df.copy()

    # Helper Series for current (TD) and yesterday (YD) data
    yd_vol = df['Volume'].shift(1)
    td_open = df['Open']

    # 1) Volume Ratios: YD Vol/5DVol, YD Vol/20D Vol
    cond1_vol = (yd_vol / df['Vol_SMA_5'].shift(1)) > 1
    cond2_vol = (yd_vol / df['Vol_SMA_20'].shift(1)) > 1
    df['F1_Vol'] = np.where(cond1_vol & cond2_vol, 2, np.where(cond1_vol | cond2_vol, 1, 0))

    # 2) Open / MA Ratios: TD Open/5D MA, TD Open/20D MA
    cond1_open = (td_open / df['SMA_5']) > 1
    cond2_open = (td_open / df['SMA_20']) > 1
    df['F2_OpenMA'] = np.where(cond1_open & cond2_open, 2, np.where(cond1_open | cond2_open, 1, 0))

    # 3) 5D MA - 20D MA (Difference logic & Swap logic)
    ma_diff = df['SMA_5'] - df['SMA_20']
    raw_f3 = np.where(ma_diff > 1, 1, np.where(ma_diff < -1, -1, 0))
    prev_f3 = pd.Series(raw_f3).shift(1)
    # Detect swapping from -1 to 1 or 1 to -1
    swap_mask_f3 = ((prev_f3 == -1) & (raw_f3 == 1)) | ((prev_f3 == 1) & (raw_f3 == -1))
    df['F3_MADiff'] = np.where(swap_mask_f3, 0, raw_f3)

    # 4) RSI Condition
    df['F4_RSI'] = np.where(df['RSI'] > 70, 1, np.where(df['RSI'] < 30, -1, 0))

    # 5) %k - %d (Difference logic & Swap logic)
    stoch_diff = df['fastk'] - df['fastd']
    raw_f5 = np.where(stoch_diff > 1, 1, np.where(stoch_diff < -1, -1, 0))
    prev_f5 = pd.Series(raw_f5).shift(1)
    # Detect swapping from -1 to 1 or 1 to -1
    swap_mask_f5 = ((prev_f5 == -1) & (raw_f5 == 1)) | ((prev_f5 == 1) & (raw_f5 == -1))
    df['F5_StochDiff'] = np.where(swap_mask_f5, 0, raw_f5)

    # 6 & 7) Stochastic %K and %D absolute thresholds
    df['F6_StochK'] = np.where(df['fastk'] > 80, 1, np.where(df['fastk'] < 20, -1, 0))
    df['F7_StochD'] = np.where(df['fastd'] > 80, 1, np.where(df['fastd'] < 20, -1, 0))

    return df

"""## 4. Target Variable Construction
We calculate the 3-day cumulative percentage change of the closing price.
To prevent data leakage, we standardize this return using a *historical rolling* mean and standard deviation.
The variable is binned into 5 distinct classes mapped to integers (0 to 4) for XGBoost.
"""

def build_target_variable(df, sd_hyperparam_1=0.8, sd_hyperparam_2=1.5):
    """Calculates standardized 3D forward returns and maps to classes 0-4."""
    df = df.copy()

    # 3D Cumulative Return for TARGET (Forward looking - shift by -3)
    df['3D_Return_Future'] = (df['Close'].shift(-3) / df['Close']) - 1

    # 3D Cumulative Return for STATS (Backward looking to prevent data leakage)
    df['3D_Return_Historical'] = (df['Close'] / df['Close'].shift(3)) - 1

    # Standardize future returns based on historical behavior (rolling 1 trading year)
    rolling_mean = df['3D_Return_Historical'].rolling(window=252, min_periods=20).mean()
    rolling_std = df['3D_Return_Historical'].rolling(window=252, min_periods=20).std()

    df['Std_3D_Return'] = (df['3D_Return_Future'] - rolling_mean) / rolling_std

    # Define conditions for target mapping
    conditions = [
        (df['Std_3D_Return'] < -sd_hyperparam_2),                             # Down > 1.5 SD -> 0 (-2 conceptually)
        (df['Std_3D_Return'] >= -sd_hyperparam_2) & (df['Std_3D_Return'] < -sd_hyperparam_1), # Down 0.8 to 1.5 SD -> 1 (-1 conceptually)
        (df['Std_3D_Return'] >= -sd_hyperparam_1) & (df['Std_3D_Return'] <= sd_hyperparam_1), # -0.8 to 0.8 SD -> 2 (0 conceptually)
        (df['Std_3D_Return'] > sd_hyperparam_1) & (df['Std_3D_Return'] <= sd_hyperparam_2),   # Up 0.8 to 1.5 SD -> 3 (1 conceptually)
        (df['Std_3D_Return'] > sd_hyperparam_2)                               # Up > 1.5 SD -> 4 (2 conceptually)
    ]

    choices = [0, 1, 2, 3, 4]
    df['Target'] = np.select(conditions, choices, default=np.nan)

    # Drop rows where target or features are NaN (e.g., very end of the dataset)
    return df.dropna()

"""## 5. Model Training (XGBoost)
We separate the data into features (X) and target (y), apply a time-series split,
and train the XGBoost model using a `multi:softmax` objective.
"""

def train_xgboost_model(df):
    """Splits data temporally and trains the XGBoost Classifier."""

    # Select feature columns dynamically based on our 'F' prefix
    feature_cols = [col for col in df.columns if col.startswith('F')]
    X = df[feature_cols]
    y = df['Target']

    # Temporal Split (80% Train, 20% Test)
    split_idx = int(len(df) * 0.8)
    X_train, X_test = X.iloc[:split_idx], X.iloc[split_idx:]
    y_train, y_test = y.iloc[:split_idx], y.iloc[split_idx:]

    # XGBoost Parameters
    params = {
        'objective': 'multi:softmax',
        'num_class': 5,
        'max_depth': 4,
        'learning_rate': 0.05,
        'subsample': 0.8,
        'random_state': 42
    }

    print("Training XGBoost Model...")
    model = xgb.XGBClassifier(**params)
    model.fit(X_train, y_train)

    # Predictions & Evaluation
    y_pred = model.predict(X_test)
    print("\nModel Evaluation on Test Set:")
    print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
    print("\nClassification Report (Classes 0-4 mapping to -2 to 2):")
    print(classification_report(y_test, y_pred))

    return model, X_train, X_test, y_train, y_test

"""## 6. Visualization
We plot the closing price alongside the 5D and 20D MAs, the RSI, and the Fast Stochastic oscillator.
We also annotate Bullish ("U") and Bearish ("D") crossover signals directly on the price chart.
"""

def plot_strategy_signals(df, start_idx=-150):
    """
    Plots the price as candlesticks, MAs, RSI, and Fast Stochastic for a subset of the data.
    Adds custom 'U' and 'D' labels for MA crossover signals.
    """
    # Slice the dataframe to view a specific window (e.g., last 150 days) for visual clarity
    plot_df = df.iloc[start_idx:].copy()

    # Determine signals for labels (5D crossing 20D)
    plot_df['Signal'] = 0
    plot_df.loc[(plot_df['SMA_5'] > plot_df['SMA_20']) & (plot_df['SMA_5'].shift(1) <= plot_df['SMA_20'].shift(1)), 'Signal'] = 1
    plot_df.loc[(plot_df['SMA_5'] < plot_df['SMA_20']) & (plot_df['SMA_5'].shift(1) >= plot_df['SMA_20'].shift(1)), 'Signal'] = -1

    # Prepare additional plots (Indicators) to append to the main mplfinance figure
    # panel=0 is the main price chart, panel=1 is the middle subplot, panel=2 is the bottom subplot
    apds = [
        mpf.make_addplot(plot_df['SMA_5'], color='blue', width=1, panel=0),
        mpf.make_addplot(plot_df['SMA_20'], color='orange', width=1, panel=0),

        # RSI on Panel 1
        mpf.make_addplot(plot_df['RSI'], panel=1, color='purple', ylabel='RSI'),
        mpf.make_addplot([70]*len(plot_df), panel=1, color='red', linestyle='--'),
        mpf.make_addplot([30]*len(plot_df), panel=1, color='green', linestyle='--'),

        # Fast Stochastic on Panel 2
        mpf.make_addplot(plot_df['fastk'], panel=2, color='blue', ylabel='Fast STC'),
        mpf.make_addplot(plot_df['fastd'], panel=2, color='orange'),
        mpf.make_addplot([80]*len(plot_df), panel=2, color='red', linestyle='--'),
        mpf.make_addplot([20]*len(plot_df), panel=2, color='green', linestyle='--')
    ]

    # Generate the candlestick plot with subplots and retrieve the Figure/Axes
    fig, axlist = mpf.plot(
        plot_df,
        type="candle", #[cite: 4]
        addplot=apds,
        figratio=(14, 12),
        panel_ratios=(2, 1, 1),
        style='yahoo',
        returnfig=True,
        title='XGBoost Forecasted Signals'
    )

    # axlist[0] corresponds to the main candlestick panel
    ax1 = axlist[0]

    # Add Custom Bullish/Bearish Labels
    # mplfinance uses sequential integer indexing for the x-axis
    for i in range(len(plot_df)):
        if plot_df['Signal'].iloc[i] == 1:
            ax1.annotate('U', (i, plot_df['SMA_5'].iloc[i]),
                         textcoords="offset points", xytext=(0,10), ha='center',
                         color='white', weight='bold',
                         bbox=dict(facecolor='green', edgecolor='none', boxstyle='round,pad=0.3'))
        elif plot_df['Signal'].iloc[i] == -1:
            ax1.annotate('D', (i, plot_df['SMA_5'].iloc[i]),
                         textcoords="offset points", xytext=(0,-15), ha='center',
                         color='white', weight='bold',
                         bbox=dict(facecolor='red', edgecolor='none', boxstyle='round,pad=0.3'))

    plt.show()

"""## 7. Main Execution Pipeline
This block calls all the helper functions in sequence, creating a readable and easily modifiable pipeline.
"""

def main():
    # 1. Fetch Data
    print(f"Fetching data for {TICKER}...")
    df_raw = fetch_stock_data(TICKER, START_DATE, END_DATE)

    # 2. Add Base Indicators
    print("Calculating technical indicators...")
    df_ta = calculate_base_indicators(df_raw)

    # 3. Engineer Custom Features
    print("Building custom features...")
    df_features = build_custom_features(df_ta)

    # 4. Construct Target Variable
    print("Constructing target variable...")
    df_final = build_target_variable(df_features, sd_hyperparam_1=0.8, sd_hyperparam_2=1.5)

    # 5. Plot Graph (Using Candlesticks)
    print("Plotting strategy indicators and signals...")
    plot_strategy_signals(df_final, start_idx=-100)

    # 6. Train and Evaluate Model
    model, X_train, X_test, y_train, y_test = train_xgboost_model(df_final)

    print("Pipeline Execution Complete.")
    return model, df_final

if __name__ == "__main__":
    trained_model, final_dataset = main()

